# Generated by Django 2.2.3 on 2019-07-13 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0002_remove_vote_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='pub_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(),
        ),
    ]
