# Generated by Django 2.2.3 on 2019-09-04 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0004_auto_20190713_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='verefied',
            field=models.BooleanField(default=0),
        ),
    ]
