# Generated by Django 2.2.3 on 2019-09-04 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0005_question_verefied'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='verefied',
        ),
    ]
