# Generated by Django 2.2.3 on 2019-09-04 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0006_remove_question_verefied'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='seen',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='verefied',
            field=models.BooleanField(default=0),
        ),
    ]
